sudo: true
language: bash

services:
  - docker

# hack to cache docker images
before_cache:
  # Save tagged docker images
  - mkdir -p $HOME/docker && docker images -a --filter='reference=wikificha/fiscalize:*' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

cache:
  bundler: true
  directories:
    - $HOME/docker

install: 
  - if [ ${TRAVIS_BRANCH} == 'master' ]; then export TAG='stable'; elif [ ${TRAVIS_BRANCH} == 'develop' ]; then export TAG='latest'; fi

stages:
jobs:
  include:
    - stage: build docker image
      script:
        - docker build --cache-from wikificha/fiscalize:$TAG -t wikificha/fiscalize:$TRAVIS_BUILD_ID .
        - docker images

    - stage: test environment
      script: 
        - docker run --rm -it wikificha/fiscalize:$TRAVIS_BUILD_ID /bin/bash -c "/opt/tools/test.sh"

    - stage: push to docker hub
      if: branch = master OR branch = develop
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker tag wikificha/fiscalize:$TRAVIS_BUILD_ID wikificha/fiscalize:$TAG 
        - docker rmi -f wikificha/fiscalize:$TRAVIS_BUILD_ID
        - docker push wikificha/fiscalize:$TAG