language: bash
sudo: true
services:
        - docker
before_install:
        - docker build --quiet=true -t wikificha/fiscalize .
script:
        - docker run --rm -it wikificha/fiscalize /bin/bash -c "/opt/tools/test.sh"
